spring:
#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/btodo
#    username: root
#    password: koreait
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp